name: CI/CD Pipeline

on:
    push:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: '18'
                  cache: 'yarn'
                  cache-dependency-path: './app/yarn.lock'

            - name: Install Deps
              working-directory: ./app
              run: yarn install

            - name: Run tests
              working-directory: ./app
              run: yarn test
              env:
                  SQLITE_DB_LOCATION: ./test-todo.db

    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: '18'
                  cache: 'yarn'
                  cache-dependency-path: './app/yarn.lock'

            - name: Install Deps
              working-directory: ./app
              run: yarn install

            - name: Build
              run: docker build -t gettting-started ./app
